/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The structured diff the UI emits on SEND/APPROVE/CANCEL. Printed verbatim to the CLI's stdout (and nothing else) so the agent can parse it. Every entry carries node/edge IDs — no prose disambiguation needed.
 */
export interface Feedback {
  /**
   * revise = apply edits and re-render · approve = apply pending edits as final touch-ups, loop ends · cancel = agent stops the loop, keeps plan as-is
   */
  action: "revise" | "approve" | "cancel";
  comments?: {
    nodeId: string;
    /**
     * May contain @NodeId mentions
     */
    text: string;
  }[];
  /**
   * Feedback the developer left on a connection (via the edge inspector). Edge-scoped counterpart of comments[]; kept separate so the agent reads a dedicated edge stream.
   */
  edgeComments?: {
    edgeId: string;
    /**
     * May contain @NodeId mentions
     */
    text: string;
  }[];
  reconnected?: {
    edgeId: string;
    /**
     * Which endpoint the dev re-dragged
     */
    end: "source" | "target";
    /**
     * Node id the endpoint pointed at before
     */
    was: string;
    /**
     * Node id the endpoint points at now
     */
    now: string;
  }[];
  deleted?: {
    nodes?: string[];
    edges?: string[];
  };
  /**
   * V1 accepts new EDGES only. New nodes are requested via comments (e.g. 'add a @PaymentRepo below this').
   */
  added?: {
    edges?: {
      from: string;
      to: string;
      kind?: string;
    }[];
  };
  moved?: {
    nodeId: string;
    toGroup: string;
  }[];
  /**
   * Free-text feedback that isn't node-specific
   */
  generalNote?: string;
}
