/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The structured diff the UI emits on SEND/APPROVE/CANCEL. Printed verbatim to the CLI's stdout (and nothing else) so the agent can parse it. Every entry carries node/edge IDs — no prose disambiguation needed.
 */
export interface Feedback {
  /**
   * revise = apply edits and re-render · approve = apply pending edits as final touch-ups, loop ends · cancel = agent stops the loop, keeps plan as-is
   */
  action: "revise" | "approve" | "cancel";
  comments?: {
    nodeId: string;
    /**
     * May contain @NodeId mentions
     */
    text: string;
  }[];
  /**
   * Feedback the developer left on a connection (via the edge inspector). Edge-scoped counterpart of comments[]; kept separate so the agent reads a dedicated edge stream.
   */
  edgeComments?: {
    edgeId: string;
    /**
     * May contain @NodeId mentions
     */
    text: string;
  }[];
  reconnected?: {
    edgeId: string;
    /**
     * Which endpoint the dev re-dragged
     */
    end: "source" | "target";
    /**
     * Node id the endpoint pointed at before
     */
    was: string;
    /**
     * Node id the endpoint points at now
     */
    now: string;
  }[];
  deleted?: {
    nodes?: string[];
    edges?: string[];
  };
  /**
   * New nodes and/or edges the developer drew on the canvas. A new node carries a client-side tempId (e.g. 'new:1'); added edges may reference that tempId as an endpoint. The agent creates each node, assigns a real id, wires the edges, and echoes the tempId → real-id mapping back so the next render shows the real name.
   */
  added?: {
    /**
     * Nodes the dev created this round. tempId is dev-side only; the agent replaces it with a real node id.
     */
    nodes?: {
      /**
       * Client-side placeholder id (e.g. 'new:1'). Referenced by added.edges until the agent assigns a real id.
       */
      tempId: string;
      label: string;
      /**
       * Same kind vocabulary as plan-graph nodes; drives the node icon.
       */
      kind: "service" | "repository" | "datastore" | "adapter" | "external" | "module" | "component" | "other";
      /**
       * Optional target group id (references graph.groups[].id)
       */
      group?: string;
      /**
       * Optional free-text intent for the new node
       */
      description?: string;
    }[];
    edges?: {
      /**
       * Source node id, or an added-node tempId
       */
      from: string;
      /**
       * Target node id, or an added-node tempId
       */
      to: string;
      kind?: string;
    }[];
  };
  moved?: {
    nodeId: string;
    toGroup: string;
  }[];
  /**
   * Free-text feedback that isn't node-specific
   */
  generalNote?: string;
}
