/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * existing = unchanged · new = added by this plan · modify = touched · delete = removed
 */
export type Status = "existing" | "new" | "modify" | "delete";

/**
 * The architecture graph the agent authors from a plan, spec, or codebase. status ∈ {existing,new,modify,delete} on nodes AND edges powers the before/after diff rendering.
 */
export interface PlanGraph {
  version: 1;
  title: string;
  groups?: {
    id: string;
    label: string;
  }[];
  nodes: Node[];
  edges: Edge[];
}
export interface Node {
  /**
   * Stable identity across rounds. The agent MUST reuse this ID when revising, or comments/layout keyed to it are lost.
   */
  id: string;
  label: string;
  /**
   * Drives the node icon (lucide). service=box, repository=archive, datastore=database, adapter=plug, external=globe.
   */
  kind: "service" | "repository" | "datastore" | "adapter" | "external" | "module" | "component" | "other";
  /**
   * References a groups[].id
   */
  group?: string;
  status: Status;
  files?: string[];
  description?: string;
}
export interface Edge {
  id: string;
  /**
   * Source node id
   */
  from: string;
  /**
   * Target node id
   */
  to: string;
  /**
   * Short relationship label rendered on the edge and shown as 'Used for' in the inspector, e.g. calls, reads, writes, depends, 'reads / writes'
   */
  kind?: string;
  status: Status;
  /**
   * Free text: what the source uses the target for. Shown as 'What it's used for' in the edge inspector. The edge-analog of node.description.
   */
  description?: string;
  /**
   * The specific methods/functions the source invokes on the target, e.g. 'charge(orderId, amount)'. Shown as 'Calls · N' in the edge inspector. The edge-analog of node.files[]. For a 'new' edge these are planned calls that may not exist yet.
   */
  calls?: string[];
}
